---
- hosts: all
  become: true
  vars:
    ansible_become_pass: "#Matilda"
  tasks:
    - name: Ensure dpkg is configured (Ubuntu)
      raw: sudo dpkg --configure -a
      ignore_errors: yes
      changed_when: false

    - name: install update and repositories (Ubuntu)
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      changed_when: false

- hosts: checkpoint
  become: true
  vars:
    ansible_become_pass: "#Matilda"
  roles:
#    - role: task1
    - role: task2
